import Head from "next/head"
import Leaderboard from "@/components/Leaderboard"
import Navbar from "@/components/Navbar"
import InputPlayerSearch from "@/components/InputPlayerSearch"
import MapRotation from "@/components/MapRotation"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div
                className="border p-6 rounded-3xl mx-auto mt-10"
                style={{ width: "fit-content" }}
            >
                <p className="mb-5">
                    Recherchez un joueur dans la base de données:
                </p>
                <InputPlayerSearch />
            </div>
            {/* <Leaderboard /> */}
            {/* <MapRotation /> */}
        </>
    )
}
