import Head from "next/head"
import Leaderboard from "@/components/Leaderboard"
import Navbar from "@/components/Navbar"
import InputPlayerSearch from "@/components/InputPlayerSearch"
import MapRotation from "@/components/MapRotation"
import Footer from "@/components/Footer"
import Predators from "@/components/Predators"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div
                className="bg-[#2c2c2c] p-10 rounded-3xl mx-auto mt-10"
                style={{ width: "fit-content" }}
            >
                <p className="mb-5 font-semibold">Recherchez un joueur:</p>
                <InputPlayerSearch />
            </div>
            {/* <Leaderboard /> */}
            <Predators />
            <MapRotation />
            <Footer />
        </>
    )
}
